service: slackoverflow

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:
  overflow:
    handler: handler.overflow
    events:
      - http:
          path: /
          method: post
